apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: calibrator
  name: calibrator
spec:
  ports:
    - name: "1890"
      port: 1890
      targetPort: 1890
  selector:
    io.kompose.service: calibrator
