version: '3.0'

volumes:
  InfluxDBData:
    driver: local 

services:
  rabbitmq:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/rabbitmq:latest
    container_name: rabbitmq-server
    build: ./incubator/communication/installation/.
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    networks:
      incubatornet:
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  influxdb-server:
    container_name: influxdb-server
    build : ./digital_twin/data_access/influxdbserver/.
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/influxdb-server:latest
    restart: always
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - InfluxDBData:/var/lib/influxdb/
    healthcheck:
      test: ["CMD", "influx", "ping", "-host", "localhost", "-port", "8086"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      incubatornet:


  incubator:
    container_name: incubator
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/incubator:latest
    build:
        context: .
        dockerfile: Dockerfile.incubator
    networks:
      incubatornet:
    ports:
      - "1884"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started
  
  lowleveldriver:
    container_name: low-level-driver
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/low-level-driver:latest
    build:
        context: .
        dockerfile: Dockerfile.lowleveldriver
    networks:
      incubatornet:
    ports:
      - "1885"
    depends_on:
      rabbitmq:
        condition: service_healthy

  influxdatarecorder:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/influx-data-recorder:latest
    container_name: influx-data-recorder
    build:
        context: .
        dockerfile: Dockerfile.influxdatarecorder
    networks:
      incubatornet:
    ports:
      - "1886"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started

  plantkalmanfilter:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/plant-kalman-filter:latest
    container_name: plant-kalman-filter
    build:
        context: .
        dockerfile: Dockerfile.plantkalmanfilter
    networks:
      incubatornet:
    ports:
      - "1887"
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  plantsimulator:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/plant-simulator:latest
    container_name: plant-simulator
    build:
        context: .
        dockerfile: Dockerfile.plantsimulator
    networks:
      incubatornet:
    ports:
      - "1888"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started
  
  simulator:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/simulator:latest
    container_name: simulator
    build:
        context: .
        dockerfile: Dockerfile.simulator
    networks:
      incubatornet:
    ports:
      - "1889"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started

  calibrator:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/calibrator:latest
    container_name: calibrator
    build:
        context: .
        dockerfile: Dockerfile.calibrator
    networks:
      incubatornet:
    ports:
      - "1890"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started

  # controllerphysicalopenloop:
  #   image: registry.gitlab.au.dk/au605331/digital-twin-incubator/controller-physical-open-loop:latest
  #   platform: linux/arm64/v8
  #   container_name: controller-physical-open-loop
  #   build:
  #       context: .
  #       dockerfile: Dockerfile.physicalopenloop
  #   networks:
  #     incubatornet:
    # ports:
    #   - "1891"
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     influxdb-server:
  #       condition: service_started

  controllerphysical:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/controller-physical:latest
    container_name: controller-physical
    build:
        context: .
        dockerfile: Dockerfile.physical
    networks:
      incubatornet:
    ports:
      - "1892"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started
  
  adaptation:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/adaptation:latest
    container_name: adaptation
    build:
        context: .
        dockerfile: Dockerfile.selfadaptationmanager
    networks:
      incubatornet:
    ports:
      - "1893"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started

  # supervisor:
  #   platform: linux/arm64/v8
  #   container_name: supervisor
  #   build:
  #       context: .
  #       dockerfile: Dockerfile.supervisor
  #   networks:
  #     incubatornet:
  #   ports:
  #     - "1894"
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     influxdb-server:
  #       condition: service_started
  
  energysaver:
    image: registry.gitlab.au.dk/au605331/digital-twin-incubator/energy-saver:latest
    container_name: energysaver
    build:
        context: .
        dockerfile: Dockerfile.energysaver
    networks:
      incubatornet:
    ports:
      - "1895"
    depends_on:
      rabbitmq:
        condition: service_healthy
      influxdb-server:
        condition: service_started

networks:
  incubatornet:
    external: false
    name: incubatornet