apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: incubator
  name: incubator
spec:
  ports:
    - name: "1884"
      port: 1884
      targetPort: 1884
  selector:
    io.kompose.service: incubator
