apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: influxdb-server
  name: influxdb-server
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    io.kompose.service: influxdb-server
