apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: influxdatarecorder
  name: influxdatarecorder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdatarecorder
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/incubatornet: "true"
        io.kompose.service: influxdatarecorder
    spec:
      containers:
        - image: localhost:5050/incubator-influx-data-recorder:latest
          name: influx-data-recorder
          ports:
            - containerPort: 1886
              protocol: TCP
      restartPolicy: Always
