apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: simulator
  name: simulator
spec:
  ports:
    - name: "1889"
      port: 1889
      targetPort: 1889
  selector:
    io.kompose.service: simulator
