apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: controllerphysical
  name: controllerphysical
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: controllerphysical
  template:
    metadata:
      labels:
        io.kompose.network/incubatornet: "true"
        io.kompose.service: controllerphysical
    spec:
      containers:
        - image: registry.gitlab.au.dk/au605331/digital-twin-incubator/controller-physical:latest
          name: controller-physical
          ports:
            - containerPort: 1892
              protocol: TCP
      restartPolicy: Always
