apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: influxdatarecorder
  name: influxdatarecorder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdatarecorder
  template:
    metadata:
      labels:
        io.kompose.network/incubatornet: "true"
        io.kompose.service: influxdatarecorder
    spec:
      containers:
        - image: registry.gitlab.au.dk/au605331/digital-twin-incubator/influx-data-recorder:latest
          name: influx-data-recorder
          ports:
            - containerPort: 1886
              protocol: TCP
      restartPolicy: Always
