apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    io.kompose.service: rabbitmq
  ports:
    - name: rabbitmq-amqp
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
    - name: rabbitmq-mqtt
      port: 1883
      targetPort: 1883
  type: ClusterIP