apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: simulator
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simulator
  template:
    metadata:
      labels:
        io.kompose.network/incubatornet: "true"
        io.kompose.service: simulator
    spec:
      containers:
        - image: registry.gitlab.au.dk/au605331/digital-twin-incubator/simulator:latest
          name: simulator
          ports:
            - containerPort: 1889
              protocol: TCP
      restartPolicy: Always
